### ISSUE TITLE
Site does not work on firefox

### ISSUE THREAD

**Issue by LogicX1** [WebAhead/wajjbat-frontend#13]
Even with permissions to access location

**Comment by LogicX1** [comment]
Interestingly I opened up TripAdvisor website to check their map , on firefox , gave them location permissions and it also did not work there , for TripAdvisor .
So possibly this issue is with our devices ?

**Comment by Karyum** [comment]
@LogicX1 so can we close this issue then ?

**Comment by LogicX1** [comment]
Yes, I looked more into into and tried to just use navigator geolocation in the console, and it is not working regardless of the site
