### ISSUE TITLE
Going to login then choosing not to login will crash the site

### ISSUE THREAD

**Issue by LogicX1** [WebAhead/wajjbat-frontend#15]
Steps to re produce  :
Go to login.
pick either Facebook or Google a popup will open to login.
close the popup 
Site will crash

**Comment by Karyum** [comment]
yeah the logging in and signing up is a big issue in the site, this issue is related to #5 .

**Comment by Karyum** [comment]
i really advise people to maker their own oauth key and help test on how we can improve this feature
[Facebook OAuth](https://developers.facebook.com/?no_redirect=1)
[Google OAuth guide](https://developers.google.com/identity/protocols/oauth2)

**Comment by LogicX1** [comment]
Solved on #23
