### ISSUE TITLE
How does create business supposed to work

### ISSUE THREAD

**Issue by LogicX1** [WebAhead/wajjbat-frontend#17]
Currently if you navigate manually to go there, you cant create a group because the returned id from the isLoggedIn is null, is this intentional ?

**Comment by Karyum** [comment]
so you are supposed to be logged in to actually add a business, and the business then needs to be approved by the admin in the CRM.
now i think you are having an issue of logging in, that's why you might be getting this weird behaviour

**Comment by LogicX1** [comment]
Sounds good
