### ISSUE TITLE
Add link to user/reviewer page.

### ISSUE THREAD

**Issue by MahmodMhamed** [WebAhead/wajjbat-frontend#27]
When the user click on reviewr name / image, should be redirected to his/her page.

relates to issue #7

**Comment by Karyum** [comment]
@MahmodMhamed i don't quite understand the user page is not the profile page. it's when you click the name of a reviewer or his profile image, then you are redirected to his profile page which is called the user page

**Comment by MahmodMhamed** [comment]
> @MahmodMhamed i don't quite understand the user page is not the profile page. it's when you click the name of a reviewer or his profile image, then you are redirected to his profile page which is called the user page

Fixed issue title and details

**Comment by hadeel11** [comment]
handled by createLink2UserPage branch.
closing the issue.

**Comment by hadeel11** [comment]
handled by createLink2UserPage branch
