### ISSUE TITLE
Build a user page 

### ISSUE THREAD

**Issue by Karyum** [WebAhead/wajjbat-frontend#7]
As a user i want to be able to click on a different user's icon or name, and be directed to their profile.
see all their past reviews and basic details.
which are :
- Name
- Picture
- Email

### Technical:
- Use the same component/page that is being used currently for the profile page.
- Maybe make a wrapper for that component so you can pass different props according to what you are trying show, profile page or user page.

**Comment by shiryz** [comment]
You should also add the list of reviews by the user so it can be viewed by other users

**Comment by MahmodMhamed** [comment]
Sub-Issues:
Add Icon to the navbar: #27
